<?xml version="1.0"?>
<robot xmlns:xacro="https://www.ros.org/wiki/xacro">
<xacro:property name="base_length" value="0.6"/>
    <xacro:property name="base_width" value="0.4"/>
    <xacro:property name="base_height" value="0.2"/>
    <xacro:property name="wheel_radius" value="0.1"/>
    <xacro:property name="wheel_length" value="0.05"/>

    <!-- Xacro Macros-->
    <xacro:macro name="wheel_link_macro" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <material name="gray"/>
            </visual>
        </link>
    </xacro:macro>

    
    <!-- Links -->
    <link name="base_footprint"/>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0"/>
            <material name="blue"/>
        </visual>
    </link>

    <xacro:wheel_link_macro prefix="right"/>
    <xacro:wheel_link_macro prefix="left"/>

    <link name="caster_wheel">
        <visual>
            <geometry>
                <sphere radius="${wheel_radius/2.0}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="gray"/>
        </visual>
    </link>

    <!-- Joints -->
    <joint name="base_link_base_footprint_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 -${wheel_length}" rpy ="0 0 0"/>
        <axis xyz="0 0 0"/>
    </joint>

    <joint name="left_wheel_base_joint" type="revolute">
        <parent link="base_link"/>
        <child link="left_wheel_link"/>
        <origin xyz="${-base_length / 4.0} ${(base_width + 0.05) / 2.0} 0" rpy="${pi / 2.0} 0 0"/>
        <axis xyz="0 0 1"/>
        <limit lower="-${pi/2.0}" upper="${pi/2.0}" velocity="100" effort="100"/>
    </joint>

    <joint name="right_wheel_base_joint" type="revolute">
        <parent link="base_link"/>
        <child link="right_wheel_link"/>
        <origin xyz="${-base_length / 4.0} ${-(base_width + 0.05) / 2.0} 0" rpy="${pi/2.0}  0 0"/>
        <axis xyz="0 0 1"/>
        <limit lower="-1.57" upper="1.57" velocity="100" effort="100"/>
    </joint>

    <joint name="caster_wheel_base_joint" type="fixed">
        <parent link="base_link"/>
        <child link="caster_wheel"/>
        <origin xyz="${base_length/3.0} 0 -0.05" rpy ="0 0 0"/>
        <axis xyz="0 0 0"/>
    </joint>
</robot>